version = 2
[plugins]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
  runtime_type = "io.containerd.runc.v2"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
{% if 'systemd' == cgroup_driver %}
  SystemdCgroup = true
{% else %}
  SystemdCgroup = false
{% endif %}

