---
- name: Setup repos
  include_tasks: "{{ zj_item }}"
  with_first_found:
    - "setup-{{ ansible_os_family }}.yaml"
    - "default.yaml"
  loop_control:
    loop_var: zj_item

- name: ensure kubernetes prereqs
  include_tasks: k8s-prereqs.yaml

- name: Install Kubernetes packages.
  become: yes
  package:
    name: "{{ zj_item.name | default(zj_item) }}"
    state: "{{ zj_item.state | default('present') }}"
  with_items: "{{ kubernetes_packages }}"
  loop_control:
    loop_var: zj_item

- name: Check if Kubernetes packages has already been initialized.
  stat:
    path: /etc/kubernetes/admin.conf
  register: kubernetes_init_stat

- name: Setup master
  include_tasks: master-setup.yaml
  when: inventory_hostname in groups["master"]

- name: Setup kubelet
  include_tasks: kubelet-setup.yaml

- name: Ensure kubelet is started and enabled at boot.
  become: yes
  service:
    name: kubelet
    state: started
    enabled: true

# Set up nodes
- name: Get the kubeadm join command from the Kubernetes master.
  command: kubeadm token create --print-join-command
  changed_when: false
  when: inventory_hostname in groups["master"]
  register: kubernetes_join_command_result

- name: Set the kubeadm join command globally.
  set_fact:
    kubernetes_join_command: >
      {{ kubernetes_join_command_result.stdout }}
      {{ kubernetes_join_command_extra_opts }}
  when: kubernetes_join_command_result.stdout is defined
  delegate_to: "{{ zj_item }}"
  delegate_facts: true
  with_items: "{{ groups['workers'] }}"
  loop_control:
    loop_var: zj_item

- name: Setup worker nodes
  include_tasks: node-setup.yaml
  when: inventory_hostname in groups["workers"]

